version: '3'

x-omnistrate-integrations:
  - omnistrateLogging:
  - omnistrateMetrics:

x-omnistrate-service-plan:
  name: 'serverless-job'
  tenancyType: 'OMNISTRATE_DEDICATED_TENANCY'
  deployment:
    hostedDeployment:
      AwsAccountId: '541226919566'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::541226919566:role/omnistrate-bootstrap-role'

services:
  serverless-job:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: $var.aws_access_key_id
      AWS_SECRET_ACCESS_KEY: $var.aws_secret_access_key
      SERVERLESS_ACCESS_KEY: $var.serverless_access_key
      SERVICE_NAME: "serverless-{{ $sys.id }}"
      ACTION: $var.action
    privileged: true
    x-omnistrate-job-config:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
    x-omnistrate-api-params:
      - key: aws_access_key_id
        description: AWS Access Key ID
        name: AWS_ACCESS_KEY_ID
        type: String
        modifiable: false
        required: true
      - key: aws_secret_access_key
        description: AWS Secret Access Key
        name: AWS_SECRET_ACCESS_KEY
        type: String
        modifiable: false
        sensitive: true
        required: true
      - key: serverless_access_key
        description: Serverless Access Key
        name: SERVERLESS_ACCESS_KEY
        type: String
        modifiable: false
        sensitive: true
        required: true
      - key: action
         description: Action
         name: ACTION
         type: String
         modifiable: true
         required: false
         defaultValue: deploy
         options:
           - deploy
           - remove

x-omnistrate-image-registry-attributes:
  ghcr.io:
    auth:
      password: ${{ secrets.GitHubPAT }}
      username: NolanJMcCafferty
